package hello;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Test;

import hello.HelloWorld;

public class HelloTest {

	@Test
	public void testHello() {
		new HelloWorld();
		assertEquals(HelloWorld.getHello(), "Hello World");
	}
}
